### ISSUE TITLE
第九章小错误

### ISSUE THREAD

**Issue by ZiHAO-LI-cmd** [helloflask/flask-tutorial#25]
教程中测试初始化数据库的代码为:  
<img width="357" alt="image" src="https://user-images.githubusercontent.com/83964237/187724770-72ceed83-8102-4ca9-99a0-fafc5fad4dd5.png">
应改为:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/83964237/187724962-ce133f8e-f7aa-404c-ad81-716736c236ab.png">

报错截图:  
<img width="559" alt="image" src="https://user-images.githubusercontent.com/83964237/187725218-8fb99b17-aa83-468c-aa13-3a830b05e021.png">

**Comment by greyli** [comment]
这里的报错是因为你的代码里少加了最后的句点：

https://github.com/ZiHAO-LI-cmd/Watchlist/blob/master/app.py#L58
