### ISSUE TITLE
Add copy button to the code blocks in docs

### ISSUE THREAD

**Issue by greyli** [helloflask/flask-tutorial#37]
Update the `mkdocs.yml` to add a copy button to the code blocks in the documentation.

Ref: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

**Comment by vimode** [comment]
The copy button for code blocks exists on this site. 
Is this issue just linking to [this repo's](https://github.com/greyli/helloflask/issues/301) issue? or did I misunderstand it?

Thank you.
